#FROM nvcr.io/nvidia/tensorflow:20.03-tf2-py3
FROM floydhub/tensorflow:1.15-gpu.cuda10cudnn7-py3_aws.54
RUN pip install git+https://github.com/JiahuiYu/neuralgym
RUN pip install opencv-python
WORKDIR /workspace
